spellchecker: aspell

matrix:
- name: markdown
  sources:
  - 'README.md'
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .config/wordlist.txt
    output: .config/dictionary.dic
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
