# source: https://github.com/sindre0830/Workflow-Templates
name: Main workflow
# when to run the workflow
on:
  push:
    paths:
    - '.github/workflows/main.yml'
    - 'src/**'
  pull_request:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.13'
        cache: 'pip'

    - name: Install dependencies
      working-directory: src
      run: |
        python -m pip install --upgrade pip flake8
        pip install -r requirements.txt

    - name: Build program
      working-directory: src
      run: python -m py_compile ./main.py

    - name: Syntax checker
      working-directory: src
      run: flake8 . --max-line-length 150
