name: Spellchecker
# when to run the workflow
on:
  push:
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2
    - uses: igsekor/pyspelling-any@v0.0.2
      name: Spellcheck
