name: Spellchecker
# when to run the workflow
on:
  push:
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  spelling:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Spellcheck
      uses: igsekor/pyspelling-any@v1.0.4

